version: '3.8'

services:
  jenkins:
    build: .
    image: custom-jenkins:lts
    network_mode: host
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker

volumes:
  jenkins_home: