pipeline {
    agent none
    stages {
        stage('Prepare') {
            agent { 
                docker {
                    image 'node:lts-alpine' 
                }
            }
            steps {
                sh 'node --version'
            }
        }
    }
}