pipeline {
    agent any
	environment {
		CI = true
	}
	stages {
		// Execute on every commit
		stage('Build') {
			steps {
				sh 'make build'
			}
		}
        stage('Tests') {
            parallel {
                stage('Lint tests') {
                    steps {
                        sh 'make lint'
                    }
                }
                stage('Unit tests') {
                    steps {
                        sh 'make unit-tests'
                    }
                }
                stage('E2E tests') {
                    steps {
                        sh 'make e2e-tests'
                    }
                }
            }
        }
	}
    post {
        cleanup {
			sh 'make clean'
            cleanWS()
        }
    }
}