pipeline {
    agent any
	environment {
		CI = true
	}
	stages {
		// Execute on every commit
		stage('Build') {
			steps {
                dir('project-1') {
				    sh 'make build'
                }
			}
		}
        stage('Lint tests') {
            steps {
                dir('project-1') {
                    sh 'make lint'
                }
            }
        }
        stage('Unit tests') {
            steps {
                dir('project-1') {
                    sh 'make unit-tests'
                }
            }
        }
        stage('E2E tests') {
            steps {
                dir('project-1') {
                    sh 'make e2e-tests'
                }
            }
        }
	}
    post {
        cleanup {
            dir('project-1') {
			    sh 'make clean'
            }
            cleanWs()
        }
    }
}